version: '3'
services:
  manager:
    build: .
    ports:
      - "8081:8080"

  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker

  jenkins:
    image: jenkins/jenkins
    ports:
      - "8090:8080"
      - "50000:50000"

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:10.0.2
    ports:
      - "8180:8080"
    environment:
      - KEYCLOAK_USER=docker
      - KEYCLOAK_PASSWORD=Docker12!
      - DB_VENDOR=h2