version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
  jenkins:
    image: jenkins/jenkins
    ports:
      - "8090:8080"
      - "50000:50000"