version: '3'
services:
  deploymentManager:


  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
  jenkins:
    image: jenkins/jenkins
    ports:
      - "8090:8080"
      - "50000:50000"
